# Generated by Django 2.1 on 2018-10-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('spesificCode', models.CharField(max_length=40, verbose_name='Spesific Code')),
                ('counter', models.IntegerField(verbose_name='Number of Download')),
                ('exportDate', models.DateTimeField(auto_now_add=True, verbose_name='Export Date')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
    ]
